#!/bin/bash
exec 2>&1
source /etc/envvars
sed -i -e "s/{{OSM_CARTO_XML_DIR}}/\/usr\/share\/mapnik\/openstreetmap-carto-$OSM_CARTO_VERSION\/style.xml/" \
       -e "s/{{PLUGINS_DIR}}/\/usr\/lib\/mapnik\/$MAPNIK_VERSION\/input\//" \
       -e "s/{{HOST}}/localhost/" \
       /usr/local/etc/renderd.conf

sed -i -e "s/{{OSM_BRIGHT_XML_DIR}}/\/usr\/share\/mapnik\/osm-bright-$OSM_BRIGHT_VERSION\/OSMBright\/style.xml/" \
       /usr/local/etc/renderd.conf

sed -i -e "s/{{OSM_CUSTOM_XML_DIR}}/\/usr\/share\/mapnik\/osm-custom\/style.xml/" \
       /usr/local/etc/renderd.conf

# osm-carto setup
cd /usr/share/mapnik/openstreetmap-carto-$OSM_CARTO_VERSION/
cp project.mml.orig project.mml

sed -i "s/\"dbname\": \"osm\"/\"host\": \"osm-db\",\n \
\"port\": \"5432\",\n \
\"user\": \"osm\",\n \
\"dbname\":\"osm\"/" project.mml
carto project.mml > style.xml

# osm-bright setup
cd /usr/share/mapnik/osm-bright-$OSM_BRIGHT_VERSION/
cp configure.py.sample configure.py

# prepare configure.py
sed -i -e "s|^config\[\"path\"\].*|config\[\"path\"\] = \"$(pwd)\"|" \
       -e "s/^config\[\"postgis\"\]\[\"host\"\].*/config\[\"postgis\"\]\[\"host\"\] = \"osm-db\"/" \
       -e "s/^config\[\"postgis\"\]\[\"port\"\].*/config\[\"postgis\"\]\[\"port\"\] = \"5432\"/" \
       -e "s/^config\[\"postgis\"\]\[\"dbname\"\].*/config\[\"postgis\"\]\[\"dbname\"\] = \"osm\"/" \
       -e "s/^config\[\"postgis\"\]\[\"user\"\].*/config\[\"postgis\"\]\[\"user\"\] = \"osm\"/" configure.py

./make.py
cd OSMBright
millstone project.mml > project.local.mml
carto project.local.mml > style.xml

exec sudo -u www-data LD_LIBRARY_PATH=/usr/local/lib/ /usr/local/bin/renderd -f --config /usr/local/etc/renderd.conf
